config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get "/historia", to: "pages#historia"
  get "/cidades", to: "pages#cidades"
  get "/patrimonio_cultural", to: "pages#patrimonio_cultural"
  get "/patrimonio_natural", to: "pages#patrimonio_natural"
  get "/legislacao", to: "pages#legislacao"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home; end

  def historia; end

  def municipios; end

  def patrimonio_cultural; end

  def patrimonio_natural; end

  def legislacao; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Regiao Administrativa de Franca</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%# fontawesome %>
     <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.1/css/all.css" crossorigin="anonymous">

     <%# bootstrap %>
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <%# google fonts %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cabin:ital,wght@0,400..700;1,400..700&family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Cabin:ital,wght@0,400..700;1,400..700&family=Montserrat:ital,wght@0,100..900;1,100..900&family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap" rel="stylesheet">

  </head>

  <body id="main-body">
    <%= render "shared/navbar"%>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <%= render "shared/footer"%>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container-home">

  <div class="home-banner p-5">
    <div class="ra-banner">
      <h1>Aglomeração Urbana de Franca (AUF)</h1>
    </div>
  </div>
  <div class="content-home p-3 ">

    <div class="home-subtitle mx-5 mb-5">
      <h1> A AUF </h1>
    </div>

    <div class="text-home1 px-5 m-2">
      <p> A <strong>Aglomeração Urbana de Franca (AUF)</strong> foi criada com a aprovação da Lei Complementar n° 1.323/2018 de 2018, o que possibilitou a institucionalização desta unidade territorial. Localizada no extremo nordeste do Estado de São Paulo, a AUF é composta por 19 municípios: Aramina, Buritizal, Cristais Paulista, Franca, Guaíra, Guará, Igarapava, Ipuã, Itirapuã, Ituverava, Jeriquara, Miguelópolis, Patrocínio Paulista, Pedregulho, Restinga, Ribeirão Corrente, Rifaina, São Joaquim da Barra e São José da Bela Vista.
      A região possui destaque no interior paulista pela integração regional, colocando a cidade de Franca como polo econômico que dinamiza a região para a promoção do desenvolvimento econômico, social, cultural e dando suporte para os cidadãos dos municípios vizinhos como acesso a serviços públicos urbanos que a cidade do calçado possa viabilizar, além de promover uma política de conservação patrimonial integrada com os municípios.
      </p>
      <div class="map-home text-center my-5">
        <%= image_tag 'mapa_auf-removebg-preview.png', alt: 'Map' %>
      </div>
      <p> De acordo com a estimativa do Perfil dos Municípios Paulista/SEADE realizada em 2018, a AUF ocupa uma área de 8.404,07 Km², comportando 645.009 habitantes. Embora tenha a participação de 1% do PIB no Estado, a região se destaca no setor da agroindústria com a produção de café e também no setor de serviços . Tendo Franca como cidade polo, o município possui um importante papel na redistribuição de produtos para os principais centros urbanos, devido à sua localização geográfica entre o Estado de MG e SP, além da dinamização econômica e a oferta de postos de trabalhos para as cidades vizinhas como Cristais Paulistas, Patrocínio Paulista, Ribeirão Corrente e entre outras.
      A economia da AUF é caracterizada pela formação de cadeias produtivas no setor da agroindústria. Sua expansão é importante para o crescimento da economia regional, mas também se faz necessário a dinamização da economia local para outros setores.
      No que se refere à distribuição de empregos, Franca concentra 56% das ocupações formais. O Produto Interno Bruto (PIB) regional foi superior a 22 milhões de reais em 2018, com a cidade de Franca concentrando 45% da geração de riqueza, seguido pelas cidades de Guaíra (14,5%)  e São Joaquim da Barra (7,6%) estão respectivamente na 2ª e 3ª posição do PIB regional, de acordo com o levantamento feito pela SDR (2021). Porém, Restinga, Ribeirão Corrente, Jeriquara, São José da Bela Vista e Aramina são as cidades mais vulneráveis e que carecem de infraestrutura urbana considerável, além dos baixos índices de ocupação em empregos formais nestes municípios. Com exceção de Ribeirão Corrente, estes mesmo municípios possuem os maiores índices de famílias que recebem o benefício do Bolsa Família.

      </p>
    </div>

  </div>

</div>

app/views/pages/legislacao.html.erb
<div class="container legal-page">
  <div class="heritage-title text-center my-5">
    <h1>Legislação</h1>
  </div>

  <div class="legal-content m-2">
    <div class="d-flex justify-content-center my-5  ">
      <div class="empty"></div>
      <div class="bra-sp heri-box text-center">
        <h3> Brasil e Estado de São Paulo </h3>
      </div>
      <div class="empty"></div>
    </div>
    <div class="decreto my-3">
      <p> Decreto-Lei N° 25/1937, de 30 de novembro de 1937 -  <strong> 1ª legislação que determina políticas de preservação do patrimônio no Brasil e a criação do SPHAN
      </strong> - <%= link_to "http://gg.gg/1botcr", "https://legis.senado.leg.br/norma/522691#:~:text=Organiza%20a%20prote%C3%A7%C3%A3o%20do%20patrim%C3%B4nio%20hist%C3%B3rico%20e%20art%C3%ADstico%20nacional.&text=AS%20ALTERA%C3%87%C3%95ES%20DECORRENTES%20DA%20LEI,DATA%20DE%20SUA%20PUBLICA%C3%87%C3%83O%20OFICIAL.&text=POLITICA%20CULTURAL%20.", target: "_blank" %>. </p>
    </div>

    <div class="decreto my-3">
      <p> Decreto-lei n° 8.534, de 2 de janeiro de 1946 - <strong> Transformação do SPHAN para DPHAN </strong> <%= link_to "http://gg.gg/1botcp", "http://gg.gg/1botcp", target: "_blank" %>. </p>
    </div>

    <div class="decreto my-3">
      <p> Decreto nº 66.967, de 27 de Julho de 1970 - <strong> Dispõe sobre a organização do Ministério de Educação e Cultura </strong> - <%= link_to "http://gg.gg/1botce", "http://gg.gg/1botce", target: "_blank" %>. </p>
    </div>

    <div class="decreto my-3">
      <p> Decreto-Lei N° 149, de 15 de agosto de 1969 - <strong> Dispõe sobre o tombamento de bens históricos do Estado de São Paulo </strong> - <%= link_to "http://gg.gg/1botc0", "http://gg.gg/1botc0", target: "_blank" %>. </p>
    </div>

    <div class="decreto my-3">
      <p> Lei Complementar N° 1.323/2018 - <strong> Criação da Aglomeração Urbana de Franca </strong> - <%= link_to "http://gg.gg/1botbd", "http://gg.gg/1botbd", target: "_blank" %>. </p>
    </div>

    <div class="decreto my-3">
      <p> Lei N° 10.247, de 22 de outubro de 1968 - <strong> Dispõe sobre o funcionamento do CONDEPHAAT-SP </strong> - <%= link_to "http://gg.gg/1boti6", "http://gg.gg/1boti6", target: "_blank" %>. </p>
    </div>

    <div class="decreto my-3">
      <p> Projeto de Lei N° 760/2023 - <strong> Determina o município de Buritizal como Interesse Turístico </strong> - Disponível em: <%= link_to "http://gg.gg/1botdb", "http://gg.gg/1botdb", target: "_blank" %>. </p>
    </div>

    <div class="decreto my-3">
      <p> Projeto de Lei N° 1.263/2019 - <strong> Fica classificado como Interesse Turístico o Município de Ipuã </strong> - <%= link_to "http://gg.gg/1botjf", "http://gg.gg/1botjf", target: "_blank" %>. </p>
    </div>

    <div class="decreto my-3">
      <p> Diário Oficial Poder Executivo - <strong> Seção I (2010) - Dispõe sobre o tombamento de conjuntos escolares do Estado de São Paulo </strong> - <%= link_to "http://gg.gg/1botf2", "http://gg.gg/1botf2", target: "_blank" %>.</p>
    </div>

    <div class="d-flex justify-content-center my-5">
      <div class="empty"></div>
      <div class="bra-auf heri-box text-center">
        <h3> AUF </h3>
      </div>
      <div class="empty"></div>
    </div>

    <div class="decreto my-3">
      <p> Lei Complementar N° 009/2008 - <strong> Plano Diretor Participativo do Município de Cristais Paulistas </strong> - <%= link_to "http://gg.gg/1botkk", "http://gg.gg/1botkk", target: "_blank" %>.</p>
    </div>

    <div class="decreto my-3">
      <p> Lei Ordinária N° 2085/2021 - <strong> Criação do Museu Histórico Municipal de Cristais Paulista </strong> - <%= link_to "http://gg.gg/1botkz", "http://gg.gg/1botkz", target: "_blank" %>.</p>
    </div>

    <div class="decreto my-3">
      <p> CONDEPHAT-Franca: Relação dos Patrimônios Tombados no Município de Franca, 2016. - <%= link_to "http://gg.gg/1b", "http://gg.gg/1b", target: "_blank" %> </p>
    </div>

    <div class="decreto my-3">
      <p> Lei Complementar 050/2003 - <strong> Plano Diretor de Franca. </strong> <%= link_to "http://gg.gg/1botm1", "http://gg.gg/1botm1", target: "_blank" %>. </p>
    </div>

    <div class="decreto my-3">
      <p> Lei Ordinária 656/1957 - <strong> Criação do Museu Histórico Municipal </strong> - <%= link_to "http://gg.gg/1botn6", "http://gg.gg/1botn6", target: "_blank" %>. </p>
    </div>

    <div class="decreto my-3">
      <p> Projeto de Lei n° 14 de 01 de junho de 1981 - <strong> Cria o Conselho de Defesa do Patrimônio Histórico, Artístico e Turístico do Município de Franca </strong> - <%= link_to "http://gg.gg/1botnx", "http://gg.gg/1botnx", target: "_blank" %>. </p>
    </div>

    <div class="decreto my-3">
      <p> Decreto Nº 8.200 de 1º de Julho de 2003 – <strong> Aprova o Regimento Interno do CONDEPHAT-Franca </strong> - <%= link_to "http://gg.gg/1boto6", "http://gg.gg/1boto6", target: "_blank" %>. </p>
    </div>

    <div class="decreto my-3">
      <p> Lei Complementar Municipal 2.882/2019 - <strong> Revisão do Plano Diretor de Guaíra. </strong> - <%= link_to "https://www.guaira.sp.gov.br/public/admin/globalarq/legislacao/arquivo/LUCOTVr.pdf", "https://www.guaira.sp.gov.br/public/admin/globalarq/legislacao/arquivo/LUCOTVr.pdf", target: "_blank" %>.</p>
    </div>

    <div class="decreto my-3">
      <p> Lei N° 1.715/1996 - <strong> Criação do Museu Municipal de Guaíra </strong> - <%= link_to "https://www.legislacaodigital.com.br/Guaira-SP/LeisOrdinarias/1715/Arquivos/1", "https://www.legislacaodigital.com.br/Guaira-SP/LeisOrdinarias/1715/Arquivos/1", target: "_blank" %>.</p>
    </div>

    <div class="decreto my-3">
      <p> Lei Complementar N° 46/2006 - <strong> Instituiu o Plano Diretor de Desenvolvimento Participativo do Município de Guará </strong> - <a href='http://gg.gg/1br0j3' target="_blank">http://gg.gg/1br0j3.</a> </p>
    </div>

    <div class="decreto my-3">
      <p> Lei N° 1539/2009 - <strong> Criação do Conselho Municipal em Defesa do Patrimônio Histórico de Guará </strong> - <a href='http://gg.gg/1br0jj' target ="_blank">http://gg.gg/1br0jj.</a> </p>
    </div>

    <div class="decreto my-3">
      <p> Lei N° 620/2014 – <strong> Criação do Conselho Municipal em Defesa do Patrimônio Histórico de Igarapava </strong> - <a href='http://gg.gg/1br0jz' target="_blank">http://gg.gg/1br0jz.</a>  </p>
    </div>

    <div class="decreto my-3">
      <p> Lei Complementar N° 031/2020 - <strong> Revisão do Plano Diretor Participativo de Ituverava </strong> - <a href='http://gg.gg/1br0kb' target="_blank">http://gg.gg/1br0kb.</a> </p>
    </div>

    <div class="decreto my-3">
      <p> Lei Complementar n° 06/2017 – <strong> Plano Diretor de Rifaina </strong> - <a href='http://gg.gg/1br0l2' target="_blank">http://gg.gg/1br0l2.</a> </p>
    </div>

    <div class="decreto my-3">
      <p>  Lei N° 1710/2015 - <strong> Plano Diretor de Turismo de Rifaina </strong> - <a href='http://gg.gg/1br0ly' target="_blank">http://gg.gg/1br0ly.</a> </p>
    </div>

  </div>

  <div class="heritage-letters my-5">
    <div class="letter-title heritage-title text-center my-4">
      <h3> Cartas do Patrimônio </h3>
    </div>
    <div class="letters my-2">
      <p> Carta de Atenas (1933) - <a href='http://gg.gg/1br0md' target="_blank">http://gg.gg/1br0md.</a> </p>
    </div>

    <div class="letters my-2">
      <p> Carta de Veneza (1964) - <a href='http://gg.gg/1br0mj' target="_blank">http://gg.gg/1br0mj.</a>  </p>
    </div>

    <div class="letters my-2">
      <p> Compromisso de Salvador (1971) - <a href='http://gg.gg/1br0uk' target="_blank">http://gg.gg/1br0uk.</a>  </p>
    </div>

    <div class="letters my-2">
      <p> Declaração de Amsterdã (1975). <a href='http://gg.gg/1br0ur' target="_blank"> http://gg.gg/1br0ur.</a>  </p>
    </div>

    <div class="letters my-2">
      <p> Normas de Quito. <a href='http://gg.gg/1br0v7' target="_blank">http://gg.gg/1br0v7.</a> </p>
    </div>

    <div class="letters my-2">
      <p> UNESCO - <strong> Convenção Para a Proteção do Patrimônio Mundial, Cultural e Natural, 1972. </strong> - <%= link_to "http://gg.gg/1br0vg", "http://gg.gg/1br0vg", target: "_blank" %>  </p>
    </div>
  </div>

</div>

app/views/shared/_footer.html.erb
<div class="container-footer">
  <div class="footer-logo p-2 align-items-center">
    <div class="footer-image m-1 text-center">
      <%= link_to root_path do %>
        <%= image_tag 'logo_auf1-removebg-preview.png', alt: 'Logo', height: '60', width: '80' %>
      <% end %>
    </div>
    </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar p-2">

  <div class="d-flex justify-content-between ms-5 me-5 align-items-center">

    <div class="nav-logo">
      <%= link_to root_path do %>
        <%= image_tag 'logo_auf1-removebg-preview.png', alt: 'Logo', height: '60', width: '80' %>
      <% end %>
    </div>

    <div class="nav-icons">
      <%= link_to "Home", root_path, class: "nav-link" %>
    </div>

    <div class="nav-icons">
      <%= link_to "Municípios", cidades_path, class: "nav-link" %>
    </div>
    <div class="nav-icons">
      <%= link_to "Patrimônio Cultural", patrimonio_cultural_path, class: "nav-link" %>
    </div>
    <%# <div class="nav-icons dropdown">
      <a class="nav-link dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
        Patrimônios
      </a>
      <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
        <li>
          <%= link_to "Patrimônio Cultural", patrimonio_cultural_path, class: "dropdown-item" %>
        <%# </li>
        <li>
          <%= link_to "Patrimônio Natural", patrimonio_natural_path, class: "dropdown-item" %>
        <%# </li>
      </ul>
    </div>  %>
    <div class="nav-icons">
      <%= link_to "Legislação", legislacao_path, class: "nav-link" %>
    </div>

  </div>

</div>